---
- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.tejaskalla.online
  tasks:
    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start and Enable MySQL server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    # check if password is set up or not
    - name: check the DB connection
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: "{{ login_host }}"
      ignore_errors: yes
      register: my_sql_connection

    - name: print output
      ansible.builtin.debug:
        msg: "{{ my_sql_connection }}"
