- name: configure frontend server
  become: yes
  hosts: frontend
  tasks:
  - name: install nginx
    apt:
    - name: nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
      
    - name: start and enable nginx
      ansible.buitin.service:
        name: nginx
        state: started
        enabled: yes

    - name: delete default website
      ansible.buitin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.buitlin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download and extract frontend code
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        