- name: configure frontend server
  become: yes
  hosts: frontend
  tasks:
  - name: install nginx
    apt:
    - name: nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
      
    - name: start and enable nginx
      ansible.buitin.service:
        name: nginx
        state: started
        enabled: yes

    - name: delete default website
      ansible.buitin.file:
        path: /usr/share/nginx/html/*
        state: absent